### ISSUE TITLE
✨ Make the operator stackable

### ISSUE THREAD

**Issue by Watch54** [AntoineJT/jasc#6]
Instead of repeating the term + (like 4 + 4 + 4 + 4), we could only add the operation once (like $+ 4 4 4 4), to see if it's useful

**Comment by AntoineJT** [comment]
Yep, it's a good idea

**Comment by AntoineJT** [comment]
Added to develop branch, needs to explain how to use in the help command, and to rewrite code, as long as I found it bad

**Comment by AntoineJT** [comment]
That is now part of the help command : issue will be closed when v0.7.0 will be released and merged to master

**Comment by AntoineJT** [comment]
That is now part of the help command : issue will be closed when v0.7.0 will be released and merged to master
